GET http://localhost:3000 HTTP/1.1
###

GET https://localhost:3000/test HTTP/1.1
###

GET https://localhost:3000/api/orders HTTP/1.1
###

GET https://localhost:3000 HTTP/1.1
###

GET https://localhost:3000/api/fruits HTTP/1.1

###
POST https://localhost:3000/api/fruits HTTP/1.1
content-type: application/json

{
    "id": "9",
    "name": "Guava"
}
###
//
DELETE https://localhost:3000/api/fruits/66fc3b74c4ec4bba7f89a645 HTTP/1.1 
###

POST https://localhost:3000/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "firstName": "testUser3",
    "lastName": "Test",
    "email": "test3@gmail.com",
    "username": "TesterUser3",
    "password": "Bingus4",
    "confirmPassword": "Bingus4",
    "accountNumber": "1234",
    "idNumber": "011212299"
}
###

POST https://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "testUser",
    "password": "theSuperSecretPassword"
}


### 
POST https://localhost:3000/api/fruits HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwidXNlcklkIjoiNjcwMjk0OTU5NGViNjEyNGYwOTZjMGFlIiwiaWF0IjoxNzI4MjI0NzIwLCJleHAiOjE3MjgyMjgzMjB9.AlTZrEFbnWY9hHZQheZwBPxXxaxIlw0KLNmxBKYKoT8

{
    "id": "48",
    "name": "Guava"
}


###
POST https://localhost:3000/api/payments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwidXNlcklkIjoiNjcwMjk0OTU5NGViNjEyNGYwOTZjMGFlIiwiaWF0IjoxNzI4MjI0NzIwLCJleHAiOjE3MjgyMjgzMjB9.AlTZrEFbnWY9hHZQheZwBPxXxaxIlw0KLNmxBKYKoT8

{
    "recieverName": "Mr FL FOX",
    "bank": "Standard Bank",
    "accNumber": "021122112",
    "payAmount": "500.00",
    "swiftCode": "STANSA33XLF"
}

###