version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a base image that is available
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
      - run:
          name: Install SonarScanner
          command: |
            # Download and unzip SonarScanner
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
            unzip sonar-scanner-cli-4.8.0.2856-linux.zip
            sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - run:
          name: Run SonarScanner
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.projectName="APDS7311_FinalPOE" \
              -Dsonar.projectVersion="1.0" \
              -Dsonar.sources="backend" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.scanner.forceEmbeddedJava=false
