version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20

jobs:
  # Job to build and test the project
  build:
    executor: node-executor
    steps:
      - checkout  # Pulls the code from your GitHub repo

      # Frontend steps
      - run:
          name: Install Frontend Dependencies
          working_directory: ./Frontend/vite-project
          command: npm install

      - run:
          name: Build Frontend
          working_directory: ./Frontend/vite-project
          command: npm run build

      # Backend steps
      - run:
          name: Install Backend Dependencies
          working_directory: ./Backend
          command: npm install

      # Optional: Run any backend or frontend tests
      - run:
          name: Run Backend Tests (if you have any)
          working_directory: ./Backend
          command: npm test

  # Job to run SonarQube scan
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh git curl
      - checkout
      - run: find .  # Optional step to verify the directory structure
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          sonar-scanner \
          -Dsonar.projectKey="APDS7311_ST10065470FinalPOE" \
          -Dsonar.projectName="APDS7311_FinalPOE" \
          -Dsonar.projectVersion="1.0" \
          -Dsonar.sources="backend" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login="${SONAR_TOKEN}" \
          -Dsonar.branch.name="${SONAR_BRANCH}"

workflows:
  # Workflow to orchestrate the jobs
  build-and-sonarqube:
    jobs:
      - build
      - sonarqube:
          requires:
            - build  # Ensures `sonarqube` runs after the `build` job
