version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20  

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Pulls the code from your GitHub repo

      # Frontend steps
      - run:
          name: Install Frontend Dependencies
          working_directory: ./Frontend/vite-project
          command: npm install

      - run:
          name: Build Frontend
          working_directory: ./Frontend/vite-project
          command: npm run build

      # Backend steps
      - run:
          name: Install Backend Dependencies
          working_directory: ./Backend
          command: npm install

      # Optional: Run any backend or frontend tests
      - run:
          name: Run Backend Tests (if you have any)
          working_directory: ./Backend
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
