# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh git curl
      - checkout
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          sonar-scanner \
          -Dsonar.projectKey="APDS7311_ST10065470FinalPOE" \
          -Dsonar.projectName="APDS7311_FinalPOE" \
          -Dsonar.projectVersion="1.0" \
          -Dsonar.sources="backend" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.exclusions="**/android/**,**/ios/**"

# Orchestrate jobs using workflows.
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
