version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd frontend
            npm install
            cd ../backend
            npm install
      - run:
          name: Run Tests
          command: |
            cd backend      

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
