version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20.18.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      
      - run:
          name: Install backend dependencies
          working_directory: ./Backend
          command: npm install
          
      - run:
          name: Install frontend dependencies
          working_directory: ./Frontend/vite-project
          command: npm install
          
      - run:
          name: Run backend tests
          working_directory: ./Backend
          command: npm run test # Update if you have a test script in package.json

      - run:
          name: Run frontend tests
          working_directory: ./Frontend/vite-project
          command: npm run test # Update if you have a test script in package.json

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
