# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: debian:latest
    resource_class: small
    steps:
      - run: apt-get update
      - run: apt-get install -y unzip wget git curl nodejs npm openjdk-17-jdk
      - run: |
          update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - run: |
          wget -O /usr/local/bin/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip && \
          unzip /usr/local/bin/sonar-scanner-cli.zip -d /usr/local && \
          mv /usr/local/sonar-scanner-*/ /usr/local/sonar-scanner && \
          ln -s /usr/local/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - checkout
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.projectName="APDS7311_FinalPOE" \
          -Dsonar.projectVersion="1.0" \
          -Dsonar.sources="backend" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.exclusions="**/android/**,**/ios/**"

# Orchestrate jobs using workflows.
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
