# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define the jobs for the pipeline.
jobs:
  # Job for running a basic "Hello, World!" example.
  say-hello:
    docker:
      - image: cimg/base:stable  # Use a stable CircleCI image.
    steps:
      - checkout  # Check out the code.
      - run:
          name: "Say hello"
          command: echo "Hello, World!"

  # Job for running a SonarQube analysis with a pre-built Docker image.
  sonarqube:
    working_directory: ~/build  # Set the working directory.
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Use the SonarQube scanner image.
    resource_class: small  # Define the resource class.
    steps:
      # Check out the code.
      - checkout
      # Run SonarQube analysis.
      - run:
          name: "Run SonarQube analysis"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.projectName="APDS7311_FinalPOE" \
              -Dsonar.projectVersion="1.0" \
              -Dsonar.sources="backend" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.exclusions="**/android/**,**/ios/**"

# Define the workflow that orchestrates the jobs.
workflows:
  version: 2  # Specify the version of the workflow.
  main-workflow:
    jobs:
      - say-hello  # Run the say-hello job first.
      - sonarqube  # Run the SonarQube job.
