version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Use a stable base image with support for installing Java
    steps:
      - checkout  # Check out the code from your repository

      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk  # Install OpenJDK 17

      - run:
          name: Run SonarScanner
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"  # Set the branch name
            echo "Sonar branch value is: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.projectName="APDS7311_FinalPOE" \
              -Dsonar.projectVersion="1.0" \
              -Dsonar.sources="backend" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.scanner.forceEmbeddedJava=false  # Force the use of local Java

workflows:
  version: 2
  build_and_analysis:
    jobs:
      - build  # Run the build job
