version: 2.1
jobs:
  build:
    docker:
      - image: sonarsource/sonar-scanner-cli:10.0.3.1430_5.0.1
    steps:
      - checkout
      - run:
          name: Check Current Directory
          command: pwd

      - run:
          name: List Top-Level Directory Structure
          command: ls -lah

      - run:
          name: List Backend Directory Structure
          command: |
            if [ -d "Backend" ]; then
              echo "Backend directory exists. Listing contents:"
              ls -lah Backend
            else
              echo "Backend directory does NOT exist. Please check the sonar.sources path."
            fi

      - run:
          name: Run SonarScanner
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"

            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.projectName="APDS7311_FinalPOE" \
              -Dsonar.projectVersion="1.0" \
              -Dsonar.sources="Backend" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.exclusions="**/android/**,**/ios/**"
